---

name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: docker build -t azdo-agent-linux .

      # removing trivy scan for now
      # see: https://github.com/microsoft/azure-pipelines-agent/issues/3385
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'azdo-agent-linux'
          format: 'table'
          # uncomment to fail on found issues with defined severity
          # exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Run the built image.
        run: docker run --name test-container --entrypoint "/bin/sleep" -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro azdo-agent-linux 60

        # TODO: simple test - need expanding
      - name: Verify tools are accessible in the built image.
        run: docker exec --tty test-container env TERM=xterm tflint --version

  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    needs: test
    name: Docker Build, Tag, Push

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: debug
      run: printenv

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # https://github.com/docker/metadata-action
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/${{ github.repository }}
        tags: |
          type=schedule,pattern={{date 'YYYYMMDD'}}
          type=sha
          type=semver,pattern={{version}}
        flavor: |
          latest=true

    - name: Push image
      uses: docker/build-push-action@v2
      with:
        tags: ${{ steps.meta.outputs.tags }}
        context: .
        push: true
